[pytest]
addopts = -vs --alluredir=./allure-results --clean-alluredir
testpaths = test_case
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    P0: core test cases
    P1: important test cases
    P2: normal test cases
